import { Router } from 'express';

const router = Router();

// Book module routes (non-TSOA routes if needed)
// Most routes are auto-generated by TSOA from controllers

// Example: Manual routes can be added here if needed
// router.get('/test', (req, res) => {
//     res.json({ message: 'Book module is working!' });
// });

export default router;
